<?php if($this->getShipment()->getIsTemando()):?>
<div class="clear">
    <div class="entry-edit">
	<div class="entry-edit-head">
	    <h4><?php echo $this->__('Temando Information'); ?></h4>
	</div>
	<div class="fieldset">
	    <table cellspacing="0" class="form-list">
		<tr>
		    <td class="label"><label><?php echo $this->__('Origin Location'); ?></label></td>
		    <td class="value"><label><strong><?php echo $this->getShipment()->getTemandoShipmentOrigin() ?></strong></label></td>
		</tr>
		<tr>
		    <td class="label"><label><?php echo $this->__('Shipment Ready Date'); ?></label></td>
		    <td class="value"><label><strong><?php echo $this->getShipment()->getTemandoShipmentReadyDate() ?></strong></label></td>
		</tr>
		<tr>
		    <td class="label"><label><?php echo $this->__('Shipment Ready Time'); ?></label></td>
		    <td class="value"><label><strong><?php echo $this->getShipment()->getTemandoShipmentReadyTime() ?></strong></label></td>
		</tr>
	    </table>     
	</div>
    </div>
</div>
<?php endif;?>