<?php

/* @var $this Ewave_Temando_Block_Adminhtml_Shipment_Edit_Tab_Form_Comment */
?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Customer Comment / Shipping Instructions'); ?></h4>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tbody>
		<tr>
		    <td class="label"><label><?php echo $this->__('Instructions')?></label></td>
		    <td class="value"><?php echo $this->getShippingInstructions() ?></td>
		</tr>
		<tr>
		    <td class="label"><label><?php echo $this->__('Comment')?></label></td>
		    <td class="value"><?php echo $this->getCustomerComment() ?></td>
		</tr>
            </tbody>
        </table>
    </div>
</div>
