<?php

/* @var $this Ewave_Temando_Block_Adminhtml_Shipment_Edit_Tab_Form_Options */
?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Customer Selected Delivery Options'); ?></h4>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tbody>
                <?php foreach ($this->getCustomerSelectedDeliveryOptions() as $_option => $_state): ?>
                    <?php /* @var $_option Ewave_Temando_Model_Option_Abstract */?>
                    <tr>
                        <td class="label"><label><?php echo $_option; ?></label></td>
                        <td class="value"><strong><?php echo $_state; ?></strong></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
