<?php
/* @var $this Ewave_Temando_Block_Adminhtml_Shipment_Edit_Tab_Form_Products */
$stockLocsJson = array();
?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Items Ordered'); ?></h4>
    </div>
</div>
<div class="grid np">
    <div class="hor-scroll">
        <table cellspacing="0" class="box np">
            <col />
            <col style="width: 100px;" />
            <col style="width: 40px;" />
            <col style="width: 70px;" />
	    <col style="width: 70px;" />
	    <col style="width: 70px;" />
            <col style="width: 70px;" />
            <col style="width: 70px;" />
            <col style="width: 70px;" />
            <thead>
                <tr class="headings">
                    <td colspan="6" style="visibility:hidden;"></td>
                    <th colspan="3" class="a-center last"><?php echo $this->__('Dimensions'); ?></th>
                </tr>
                <tr class="headings">
                    <th><?php echo $this->__('Product'); ?></th>
                    <th><?php echo $this->__('SKU'); ?></th>
                    <th class="a-center"><?php echo $this->__('Qty'); ?></th>
		    <th><?php echo $this->__('Availability');?></th>
		    <th class="a-center"><?php echo $this->__('Qty to Ship'); ?></th>
                    <th class="a-center"><?php echo $this->__('Weight'); ?></th>
                    <th class="a-center"><?php echo $this->__('Height'); ?></th>
                    <th class="a-center"><?php echo $this->__('Length'); ?></th>
                    <th class="a-center last"><?php echo $this->__('Width'); ?></th>
                </tr>
            </thead>
            <?php $_i = 0; foreach ($this->getShipment()->getOrder()->getItemsCollection() as $_item): ?>
                <tbody>
                <?php if (!$_item->getParentItem()): /* @var $_item Mage_Sales_Model_Order_Item */ ?>
                    <?php 
			$_isAvailable = false;
			$_product = $this->getProductFromItem($_item);
			$_productId = $this->getProductId($_item, $_product);
			
			$shipQty = null;
			$qtyToShip = Mage::getSingleton('adminhtml/session')->getData('qty_to_ship_'.$this->getRequest()->getParam('id'));
			if(is_array($qtyToShip) && array_key_exists($_productId, $qtyToShip)) {
			    $shipQty = (int) $qtyToShip[$_productId];
			} else {
			    $shipQty = $_item->getQtyToShip();
			}
		    ?>
                    <tr class="<?php echo ++$_i % 2 ? 'odd' : 'even'; ?>">
                        <td><?php echo $_item->getName(); ?></td>
                        <td><?php echo $_item->getSku(); ?></td>
                        <td>
			    <span class="nobr">
				<?php if ($_item->getQtyOrdered() > 0): ?>
				    <?php echo $this->__('Ordered'); ?>: <strong><?php echo $_item->getQtyOrdered()*1 ?></strong><br />
				<?php endif; ?>
				<?php if ($_item->getQtyShipped() > 0): ?>
				    <?php echo $this->__('Shipped'); ?>: <strong><?php echo $_item->getQtyShipped()*1 ?></strong><br />
				<?php endif; ?>
				<?php if ($_item->getQtyCanceled() > 0): ?>
				    <?php echo $this->__('Canceled'); ?>: <strong><?php echo $_item->getQtyCanceled()*1 ?></strong><br />
				<?php endif; ?>
				<?php if ($_item->getQtyRefunded() > 0): ?>
				    <?php echo $this->__('Refunded'); ?>: <strong><?php echo $_item->getItem()->getQtyRefunded()*1 ?></strong><br />
				<?php endif; ?>
			    </span>
			</td>
			<td>
			    <span class="nobr">
				<?php $stockLocsJson = array_merge($stockLocsJson, $this->getStockLocationsJson($_productId)) ?>
				<?php foreach($this->getStockLocations($_productId) as $warehouse):?>
				<?php /* @var $warehouse Ewave_Temando_Model_Warehouse */ ?>
				    <?php echo $warehouse->getName() . '<br/>'; $_isAvailable = true ?>
				<?php endforeach; ?>
			    </span>
			</td>
			<td><input class="input-text" type="text" id="qty_to_ship_<?php echo $_productId ?>" <?php /*if(!$_isAvailable) {echo "disabled='disabled'";}*/ ?> name="qty_to_ship[<?php echo $_productId ?>]" value="<?php echo $shipQty ?>" />
                        <td><?php echo (float)$_item->getWeight() . ' ' . $this->getWeightUnitText(); ?></td>
                        <td><?php echo (float)$_product->getTemandoHeight() . ' ' . $this->getMeasureUnitText(); ?></td>
                        <td><?php echo (float)$_product->getTemandoLength() . ' ' . $this->getMeasureUnitText(); ?></td>
                        <td class="last"><?php echo (float)$_product->getTemandoWidth() . ' ' . $this->getMeasureUnitText(); ?></td>
                    </tr>
                <?php endif; ?>
                </tbody>
            <?php endforeach; ?>
        </table>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var shipment = new Shipment(
	<?php echo Mage::helper('core')->jsonEncode($stockLocsJson); ?>,
	"warehouse_id"
    );
    shipment.warehouseDropdownChangeListener();
//]]>

</script>
